### ISSUE TITLE
Utilización antes de asignación

### ISSUE THREAD

**Issue by camilog** [clcert/psifos-backend-op#14]
https://github.com/clcert/psifos-backend-op/blob/dev/app/psifos/utils.py#L50

Es simplemente un typo o implica algo más?
Creo que nunca lo habíamos probado con más de un trustee

**Comment by camilog** [comment]
@JaramilloCris @Lomolisso Ahora que lo veo mejor, la variable `a_combined_pk` no se utiliza después, y se crea la variable `combined_pk` que no involucra nada de lo hecho en las líneas 48, 49 y 50.

Por ende, mi solución sería borrar esas líneas 48, 49 y 50, y luego probar si la generación de la clave se hace de manera exitosa

**Comment by Lomolisso** [comment]
@camilog efectivamente eso es lo que hay que hacer. Probablemente es un resto de algún merge que hicimos.

**Comment by camilog** [comment]
Fixed by f7b26b7
