### ISSUE TITLE
Pregunta con mn con opciones repetidas

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-backend-op#29]
REPRO
Crear una pregunta con mn que tenga las siguientes opciones.
```
Jaume Vidal,Candidaturas Oficiales
Jaume Vidal,Candidaturas Oficiales
Jaume Vidal,Candidaturas Oficiales
Jaume Vidal,Candidaturas Oficiales
Jaume Vidal,Candidaturas Oficiales
Jaume Vidal,Candidaturas Oficiales
Alipio Vargas,Candidaturas Oficiales
Alipio1 Vargas,Candidaturas otro tipo
Alipio2 Vargas,Candidaturas otro tipo
Alipio3 Vargas,Candidaturas otro tipo
Alipio4 Vargas,Candidaturas otro tipo
```
(Jaume Vidal,Candidaturas Oficiales se repite muchas veces)

ESPERADO
No se puede crear la pregunta con opciones repetidas

BUG
La pregunta se crea exitosamente y se puede dar inicio a la elección, pero no finalizarla.

**Comment by camilog** [comment]
Lo que determinó @JaramilloCris fue que se filtraran las opciones repetidas vía frontend, lo cual considero que es una buena solución https://github.com/clcert/psifos-frontend/pull/137
