### ISSUE TITLE
Generar bundle a pesar de faltar desencriptaciones

### ISSUE THREAD

**Issue by camilog** [clcert/psifos-backend-op#44]
Actualmente, el sistema tira un error cuando trato de descargar el bundle de una elección donde un custodio de clave no participó, es decir, su campo decryptions está vacío.
El sistema debe permitir descargar el bundle, dejando vacío ese valor. El verificador soporta esto y de igual manera puede verificar la elección

**Comment by JaramilloCris** [comment]
@camilog Este se arreglo en el backend info, como era una linea lo pushie directo a dev
