### ISSUE TITLE
Añadir ruta para descargar archivo bundle

### ISSUE THREAD

**Issue by camilog** [clcert/psifos-backend-op#7]
Una vez finalizada la elección, el administrador puede pedir (apretando un botón en su panel) que se genere el archivo bundle.
Este archivo bundle es un JSON que posee la siguiente estructura:
```
"election": <election_info>,
"voters": <voters_info>,
"votes": <cast_votes_info>,
"result": <election_result>,
"trustees": <trustee_info>
```
Cada uno de los <info> es la misma información que entregamos actualmente en varios endpoints repartidos. 
Por último, cada uno de los <info> está codificado en base64, con el objetivo de reducir el tamaño del archivo resultante.

Esto también va a implicar unos cambios mínimos al frontend

**Comment by JaramilloCris** [comment]
Voy a necesitar que campos quieres de todo, onda la elecion tiene varios campos igual que los votes, trustees, etc. Si me das un ejemplo te lo agradeceria :cat:
